### ISSUE TITLE
Add a little exercise (optional) using the JVM sync library

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-jvm-sdk-hands-on#14]
Goal:  Load a minimum CSV  that contains only data that map to standard CTP fields (independent of pruduct type) and have them stream load it, transform to drafts and feed these in.  

The loading of the CSV into a stream can be part of the exercise already-

**Comment by nkuehn** [comment]
```
productType,productId,inventoryId,articleId,productName,productDescription,basePrice,currencyCode,imageUrl
standard,yourName-P1,yourName-SKU101,yourName-A101,Shirt,"You will look good in this","1123.35",EUR,https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/081455_1_medium.jpg
standard,yourName-P1,yourName-SKU102,yourName-A102,Shirt,"You will look good in this","1000.00",EUR,https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/081455_1_medium.jpg

```

**Comment by heshamMassoud** [comment]
Addressed already:  https://github.com/commercetools/commercetools-jvm-sdk-training/blob/starter-project-exercises/src/main/java/handson/Exercise10.java
