### ISSUE TITLE
Broken JavaDoc link

### ISSUE THREAD

**Issue by allcentury** [sphereio/sphere-jvm-sdk-hands-on#4]
The link in this [readme](https://github.com/commercetools/commercetools-jvm-sdk-training/blob/master/src/test/java/crud/lecture3_query/README.md) (and most other README's I've seen thus far) results in a 404.  I'm not sure if the javadoc's are hosted elsewhere or if it should point to [our jvm docs](http://dev.commercetools.com/jvm/#query).

**Comment by katmatt** [comment]
Closing abandoned issue.
